spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

aws.region=ap-south-1
aws.s3.bucket=careerpathai-resumes-112401921583
aws.dynamodb.table=Resumes

aws.cognito.userPoolId=ap-south-1_yxdhYhDzV
aws.cognito.clientId=3uhfeb6dn269f7bdrscjr6vpg2
aws.cognito.region=ap-south-1

# Cognito JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_yxdhYhDzV